name: Build and Publish

on:
  push:
    branches:
      - 'master'

jobs:
  cancel:
    name: "Cancel previous workflow runs"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          workflow_id: build.yaml
          access_token: ${{ github.token }}

  build_container_image:
    name: "Build and publish rpm-ostree container image"
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_PAT }}

      - name: Build and push rpm-ostree container image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: |
            rpm-ostree:latest

      - name: Determine build information
        id: build_info
        shell: bash
        run: |
          set -ueo pipefail

          rpm_ostree_version="$(docker run --rm rpm-ostree:latest 'rpm-ostree --version' | sed -En -e '/^.*Version:/!d' -e \"s/.*Version:\s+'([^']+)'.*/\1/\"  -e p)"
          echo "::debug::Setting rpm_ostree_version to ${rpm_ostree_version}"
          echo "::set-output name=rpm_ostree_version::${rpm_ostree_version}"
          
          ostree_version="$(docker run --rm rpm-ostree:latest 'ostree --version' | sed -En -e '/^.*Version:/!d' -e \"s/.*Version:\s+'([^']+)'.*/\1/\"  -e p)"
          echo "::debug::Setting ostree_version to ${ostree_version}"
          echo "::set-output name=ostree_version::${ostree_version}"

      - name: Build and push rpm-ostree container image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/rpm-ostree:${{ steps.build_info.outputs.rpm_ostree_version }}-{{ steps.build_info.outputs.ostree_version }}
